[package]
edition = "2021"
name = "bevy_magic_light_2d"
version = "0.4.2"

[features]
default = ["egui"]
egui = ["dep:bevy_egui", "dep:bevy-inspector-egui", "dep:bevy-inspector-egui-derive", "dep:egui"]

[dependencies]
anyhow = "1.0.75"
bevy = { version = "0.11.2", default-features = false, features = [
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_winit",
  "bevy_asset",
  "bevy_sprite",
  "bevy_pbr",
] }
bevy_egui = { version = "0.21", default-features = false, optional = true }
bevy-inspector-egui = { version = "0.19.0", optional = true }
bevy-inspector-egui-derive = { version = "0.19", optional = true }
egui = { version = "0.22", features = ["bytemuck"], optional = true }
encase = "0.6.1"
log = "0.4.20"
rand = "0.8.5"

[dev-dependencies]
bevy = "0.11"

[profile.release]
codegen-units = 1
debug = false
lto = "thin"
opt-level = 3
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
debug = true
incremental = true

[profile.dev]
codegen-units = 16
opt-level = 0
debug = true
incremental = true
